version: '3.8'
services:
# -------------------------------------------
  # list of the all containers
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - '5000:5000'
    env_file:
      - ./.env.prod
# -------------------------------------------
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      # for windows to update after save
      - CHOKIDAR_USEPOOLING=true
    env_file:
      - ./.env.prod
    links:
      - backend

# -------------------------------------------